go get -v github.com/golang/protobuf/protoc-gen-go
go get -v github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go get -v github.com/gogo/protobuf/protoc-gen-gofast
go get -v github.com/gogo/protobuf/proto
go get -v github.com/gogo/protobuf/gogoproto
go get -v github.com/gogo/protobuf/protoc-gen-gogo
go get -v github.com/gogo/protobuf/protoc-gen-gogofast
go get -v golang.org/x/tools/present
go get -v golang.org/x/tools/cmd/goimports
go get -v golang.org/x/lint/golint
go get -v github.com/LK4D4/vndr
go get -v github.com/stevvooe/protobuild
go get -v github.com/mdempsky/gocode
