#!/bin/bash
uptime_formatted=$(uptime | cut -d ',' -f1  | cut -d ' ' -f4,5)
date_formatted=$(date "+%a %F %H:%M")

linux_version=$(uname -r | cut -d '-' -f1)

# batter
battery_info=$(upower --show-info $(upower --enumerate |\
grep 'BAT') |\
egrep "percentage" |\
awk '{print $2}')

battery_state=$(upower --show-info $(upower --enumerate | grep BAT) | grep state | awk '{ print $2; }')
if [ "$battery_state" = "discharging" ]; then
    battery_left=$(upower --show-info $(upower --enumerate | grep BAT) | grep "time to empty" | awk '{ print $4, $5; }')
    battery_info="$battery_info $battery_left"
fi

# audio
audio_volume=$(amixer -M get Master |\
awk '/Mono.+/ {print $6=="[off]" ?\
$4" 🔇": \
$4" 🔉"}' |\
tr -d [])

load=$(cat /proc/loadavg | awk -F ' ' '{print $2}')

# network
default_iface=$(ip r s | grep default | head -1 | awk '{ print $5; }')
ip=$(ip a s $default_iface | grep -e inet | head -1 | awk '{ print $2; }')
# ethernet
if [[ "$default_iface" == *"eth"* ]] || [[ "$default_iface" == *"ens"* ]]; then
	speed=$(ethtool $default_iface 2>/dev/null | grep -i speed | awk '{ print $2; }')
else # wifi
	speed="📶 $(iwlist $default_iface rate | grep -v wlan0 | head -1 | awk '{ print $3; }' | cut -d'=' -f2 | cut -d'.' -f1)Mb/s"
fi

echo -e $ip "|" $speed  "|" $load "|" $linux_version "|" $audio_volume "|" $battery_info 🔋 "|" $date_formatted
