#!/bin/bash
mode=$1
$(lsmod | grep qxl > /dev/null)
if [ $? == 0  ]; then
    if [ "$(xrandr | grep 1920)" = ""  ]; then
        xrandr --newmode "1920" 172.51  1920 2040 2248 2576  1080 1081 1084 1118  -HSync +Vsync
        xrandr --addmode Virtual-0 1920
    fi
    if [ "$(xrandr | grep 2560)" = ""  ]; then
        xrandr --newmode "2560" 311.31  2560 2744 3024 3488  1440 1441 1444 1490  -HSync +Vsync
        xrandr --addmode Virtual-0 2560
    fi

    case $mode in
        window)
            $(xrandr --output Virtual-0 --mode 1920)
            if [ $? == 0 ]; then
                # sometimes resolutions are detected and do not need to be added
                xrandr --output Virtual-0 --mode 1920x1080
            fi
            ;;
        *)
            $(xrandr --output Virtual-0 --mode 2560)
            if [ $? == 0 ]; then
                xrandr --output Virtual-0 --mode 2560x1440
            fi
            ;;
    esac
fi
