#!/bin/bash
mode=$1
MODE_WINDOW="1920x1080_vm"
MODE_FULL="2560x1440_vm"
$(lsmod | grep qxl > /dev/null)
if [ $? == 0  ]; then
    if [ "$(xrandr | grep $MODE_WINDOW)" = ""  ]; then
        xrandr --newmode "$MODE_WINDOW" 173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
        xrandr --addmode Virtual-0 $MODE_WINDOW
    fi
    if [ "$(xrandr | grep $MODE_FULL)" = ""  ]; then
        xrandr --newmode "$MODE_FULL" 492.00  3200 3456 3800 4400  1800 1803 1808 1865 -hsync +vsync
        xrandr --addmode Virtual-0 $MODE_FULL
    fi

    case $mode in
        window)
            xrandr --output Virtual-0 --mode $MODE_WINDOW
            ;;
        *)
            xrandr --output Virtual-0 --mode $MODE_FULL
            ;;
    esac
fi
