#!/bin/bash
if [ -f "/etc/redhat-release" ]; then
    ROOT_DISK=`df -h | grep root | awk '{ print $5; }'`
    HOME_DISK=`df -h | grep home | awk '{ print $5;  }'`
else
    ROOT_DISK=`df -h | grep disk1 | awk '{ print $4; }'`
fi

INFO=""
if [ ! -z "$ROOT_DISK" ]; then
    INFO="/:$ROOT_DISK"
fi

if [ ! -z "$HOME_DISK" ]; then
    INFO="$INFO ~:$HOME_DISK"
fi

echo -e $INFO
