#!/bin/bash
LOG=/tmp/dock.log

log() {
    echo "`date`: $1" >> $LOG
}

log "detected event.  checking config."

reload(){
    # reload i3
    USER_ID=`id -u $USR`
    SOCKET=`ls /run/user/$USER_ID/i3/ipc-socket.*`
    log "reloading socket $SOCKET for user $USER_ID"
    i3-msg -s $SOCKET reload > /dev/null
}

for USR in `find /home/ -maxdepth 1 -exec basename {} \; | tail -n +2`; do
    CFG="/home/$USR/.i3/config"
    log "checking for $CFG"

    if [ -e "$CFG" ]; then
        for hid in 0 1 2 3 4 5; do
            INFO=`udevadm info -a /dev/hidraw$hid | grep HHKB`
            STATUS=$?
            if [ "$STATUS" != "0" ]; then
                log "setting config for mod1"
                setxkbmap -layout us
            fi

            HHKB=`echo $INFO | grep HHKB`
            if [ ! -z "$HHKB" ]; then
                log "setting config for mod4"
                sed -i 's/\$mod Mod.*/\$mod Mod4/g' $CFG
                xmodmap ~/.dotfiles/linux/xmodmap.hhkb
                reload
                break
            else
                log "setting config for mod1"
                setxkbmap -layout us
                reload
            fi
        done
    fi
done

