#!/bin/bash
LOG=/tmp/dock.log

log() {
    echo "`date`: $1" >> $LOG
}

log "detected event.  checking config."

for USR in `find /home -maxdepth 1 -exec basename {} \; | tail -n +2`; do
    CFG="/home/$USR/.i3/config"
    log "checking for $CFG"

    if [ -e "$CFG" ]; then
        udevadm info -a /dev/hidraw3 > /dev/null 2>&1
        STATUS=$? 
        if [ "$STATUS" = "0" ]; then
            log "setting config for mod4"
            sed -i 's/\$mod Mod.*/\$mod Mod4/g' $CFG
        else
            log "setting config for mod1"
            sed -i 's/\$mod Mod.*/\$mod Mod1/g' $CFG
        fi

        # reload i3
	USER_ID=`id -u $USR`
        SOCKET=`ls /run/user/$USER_ID/i3/ipc-socket.*`
	log "reloading socket $SOCKET for user $USER_ID"
        i3-msg -s $SOCKET reload
    fi
done
